# Generated by Django 3.2.7 on 2021-09-29 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('about', models.CharField(max_length=255)),
                ('personal_skill1', models.CharField(max_length=20)),
                ('personal_skill2', models.CharField(max_length=20)),
                ('personal_skill3', models.CharField(max_length=20)),
                ('personal_skill4', models.CharField(max_length=20)),
                ('personal_skill1_bar1', models.IntegerField()),
                ('personal_skill1_bar2', models.IntegerField()),
                ('personal_skill1_bar3', models.IntegerField()),
                ('personal_skill1_bar4', models.IntegerField()),
                ('professional_skill1', models.CharField(max_length=20)),
                ('professional_skill2', models.CharField(max_length=20)),
                ('professional_skill3', models.CharField(max_length=20)),
                ('professional_skill4', models.CharField(max_length=20)),
                ('professional_skill1_bar1', models.IntegerField()),
                ('professional_skill1_bar2', models.IntegerField()),
                ('professional_skill1_bar3', models.IntegerField()),
                ('professional_skill1_bar4', models.IntegerField()),
                ('education_time1', models.DateField()),
                ('education_time2', models.DateField()),
                ('education_time3', models.DateField()),
                ('education_time4', models.DateField()),
                ('education_comp1', models.CharField(max_length=50)),
                ('education_comp2', models.CharField(max_length=50)),
                ('education_comp3', models.CharField(max_length=50)),
                ('education_comp4', models.CharField(max_length=50)),
                ('education_des1', models.CharField(max_length=80)),
                ('education_des2', models.CharField(max_length=80)),
                ('education_des3', models.CharField(max_length=80)),
                ('education_des4', models.CharField(max_length=80)),
                ('work_time1', models.DateField()),
                ('work_time2', models.DateField()),
                ('work_time3', models.DateField()),
                ('work_time4', models.DateField()),
                ('work_comp1', models.CharField(max_length=50)),
                ('work_comp2', models.CharField(max_length=50)),
                ('work_comp3', models.CharField(max_length=50)),
                ('work_comp4', models.CharField(max_length=50)),
                ('work_des1', models.CharField(max_length=80)),
                ('work_des2', models.CharField(max_length=80)),
                ('work_des3', models.CharField(max_length=80)),
                ('work_des4', models.CharField(max_length=80)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
